services:
  paste:
    container_name: paste
    build:
      args:
        NEXT_PUBLIC_FRONTEND_URL: https://my-domain.com
        NEXT_PUBLIC_OPENAI_SYNTAX_DETECTION: False # Set to True to enable OpenAI syntax detection
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@database.com:5432/postgres
      # Uncomment the following line and replace the value with your OpenAI API key
      # OPENAI_API_KEY: sk-1234567890abcdef1234567890abcdef
      PORT: ${PORT:-3000}

