services:
  paste:
    container_name: paste
    build:
      args:
        NEXT_PUBLIC_FRONTEND_URL: https://my-domain.com
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@database.com:5432/postgres
      PORT: ${PORT:-3000}

