# Build plan

providers = ["node"]

[variables]
CI = "true"
NIXPACKS_METADATA = "node"
NODE_ENV = "production"

[phases.setup]
nixPkgs = [
    "nodejs_22",
    "yarn-1_x",
    "openssl",
]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "npm install -g corepack@0.24.1 && corepack enable",
    "yarn install --check-cache --immutable",
]

[phases.build]
dependsOn = ["install"]
cmds = ["yarn run build"]

[start]
cmd = "yarn run migrate && yarn run start"

